// Code generated by MockGen. DO NOT EDIT.
// Source: node-registrar/pkg/db/db.go
//
// Generated by this command:
//
//	mockgen -source=node-registrar/pkg/db/db.go -destination=node-registrar/pkg/mocks/mock_db.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	pq "github.com/lib/pq"
	db "github.com/threefoldtech/tfgrid4-sdk-go/node-registrar/pkg/db"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDB) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDB)(nil).Close))
}

// CreateAccount mocks base method.
func (m *MockDB) CreateAccount(account *db.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", account)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockDBMockRecorder) CreateAccount(account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockDB)(nil).CreateAccount), account)
}

// CreateFarm mocks base method.
func (m *MockDB) CreateFarm(farm db.Farm) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFarm", farm)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFarm indicates an expected call of CreateFarm.
func (mr *MockDBMockRecorder) CreateFarm(farm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFarm", reflect.TypeOf((*MockDB)(nil).CreateFarm), farm)
}

// CreateUptimeReport mocks base method.
func (m *MockDB) CreateUptimeReport(report *db.UptimeReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUptimeReport", report)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUptimeReport indicates an expected call of CreateUptimeReport.
func (mr *MockDBMockRecorder) CreateUptimeReport(report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUptimeReport", reflect.TypeOf((*MockDB)(nil).CreateUptimeReport), report)
}

// GetAccount mocks base method.
func (m *MockDB) GetAccount(twinID uint64) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", twinID)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockDBMockRecorder) GetAccount(twinID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockDB)(nil).GetAccount), twinID)
}

// GetAccountByPublicKey mocks base method.
func (m *MockDB) GetAccountByPublicKey(publicKey string) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByPublicKey", publicKey)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByPublicKey indicates an expected call of GetAccountByPublicKey.
func (mr *MockDBMockRecorder) GetAccountByPublicKey(publicKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByPublicKey", reflect.TypeOf((*MockDB)(nil).GetAccountByPublicKey), publicKey)
}

// GetFarm mocks base method.
func (m *MockDB) GetFarm(farmID uint64) (db.Farm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFarm", farmID)
	ret0, _ := ret[0].(db.Farm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFarm indicates an expected call of GetFarm.
func (mr *MockDBMockRecorder) GetFarm(farmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFarm", reflect.TypeOf((*MockDB)(nil).GetFarm), farmID)
}

// GetNode mocks base method.
func (m *MockDB) GetNode(nodeID uint64) (db.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNode", nodeID)
	ret0, _ := ret[0].(db.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNode indicates an expected call of GetNode.
func (mr *MockDBMockRecorder) GetNode(nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNode", reflect.TypeOf((*MockDB)(nil).GetNode), nodeID)
}

// GetUptimeReports mocks base method.
func (m *MockDB) GetUptimeReports(nodeID uint64, start, end time.Time) ([]db.UptimeReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUptimeReports", nodeID, start, end)
	ret0, _ := ret[0].([]db.UptimeReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUptimeReports indicates an expected call of GetUptimeReports.
func (mr *MockDBMockRecorder) GetUptimeReports(nodeID, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUptimeReports", reflect.TypeOf((*MockDB)(nil).GetUptimeReports), nodeID, start, end)
}

// GetZOSVersion mocks base method.
func (m *MockDB) GetZOSVersion() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZOSVersion")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZOSVersion indicates an expected call of GetZOSVersion.
func (mr *MockDBMockRecorder) GetZOSVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZOSVersion", reflect.TypeOf((*MockDB)(nil).GetZOSVersion))
}

// ListFarms mocks base method.
func (m *MockDB) ListFarms(filter db.FarmFilter, limit db.Limit) ([]db.Farm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFarms", filter, limit)
	ret0, _ := ret[0].([]db.Farm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFarms indicates an expected call of ListFarms.
func (mr *MockDBMockRecorder) ListFarms(filter, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFarms", reflect.TypeOf((*MockDB)(nil).ListFarms), filter, limit)
}

// ListNodes mocks base method.
func (m *MockDB) ListNodes(filter db.NodeFilter, limit db.Limit) ([]db.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNodes", filter, limit)
	ret0, _ := ret[0].([]db.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNodes indicates an expected call of ListNodes.
func (mr *MockDBMockRecorder) ListNodes(filter, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNodes", reflect.TypeOf((*MockDB)(nil).ListNodes), filter, limit)
}

// MigrateNodeLastSeen mocks base method.
func (m *MockDB) MigrateNodeLastSeen() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateNodeLastSeen")
	ret0, _ := ret[0].(error)
	return ret0
}

// MigrateNodeLastSeen indicates an expected call of MigrateNodeLastSeen.
func (mr *MockDBMockRecorder) MigrateNodeLastSeen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateNodeLastSeen", reflect.TypeOf((*MockDB)(nil).MigrateNodeLastSeen))
}

// RegisterNode mocks base method.
func (m *MockDB) RegisterNode(node db.Node) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterNode", node)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterNode indicates an expected call of RegisterNode.
func (mr *MockDBMockRecorder) RegisterNode(node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterNode", reflect.TypeOf((*MockDB)(nil).RegisterNode), node)
}

// SetZOSVersion mocks base method.
func (m *MockDB) SetZOSVersion(version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetZOSVersion", version)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetZOSVersion indicates an expected call of SetZOSVersion.
func (mr *MockDBMockRecorder) SetZOSVersion(version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetZOSVersion", reflect.TypeOf((*MockDB)(nil).SetZOSVersion), version)
}

// Transaction mocks base method.
func (m *MockDB) Transaction(fn func(*gorm.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockDBMockRecorder) Transaction(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockDB)(nil).Transaction), fn)
}

// UpdateAccount mocks base method.
func (m *MockDB) UpdateAccount(twinID uint64, relays pq.StringArray, rmbEncKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", twinID, relays, rmbEncKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockDBMockRecorder) UpdateAccount(twinID, relays, rmbEncKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockDB)(nil).UpdateAccount), twinID, relays, rmbEncKey)
}

// UpdateFarm mocks base method.
func (m *MockDB) UpdateFarm(farmID uint64, name, stellarAddr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFarm", farmID, name, stellarAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFarm indicates an expected call of UpdateFarm.
func (mr *MockDBMockRecorder) UpdateFarm(farmID, name, stellarAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFarm", reflect.TypeOf((*MockDB)(nil).UpdateFarm), farmID, name, stellarAddr)
}

// UpdateNode mocks base method.
func (m *MockDB) UpdateNode(nodeID uint64, node db.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNode", nodeID, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNode indicates an expected call of UpdateNode.
func (mr *MockDBMockRecorder) UpdateNode(nodeID, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNode", reflect.TypeOf((*MockDB)(nil).UpdateNode), nodeID, node)
}
